MYSQL_CONFIG:
  name: 'dida-mysql-dev'
  type: 'mysql'
  host: 'localhost'
  port: 3306
  username: 'root'
  password: 'dd123456'
  database: 'dida-dev'
  timezone: '+08:00'
  # 这里的命名一定要跟 MongoDB 里面的配置命名区分开
  entities: 'mysql'
  synchronize: true

REDIS_CONFIG:
  host: 'localhost'
  port: 6379
  database: 'login_user'
  password: ''
  # 单位是秒,默认是1day = 60 * 60 * 24
  ttl: 86400

JWT:
  secret: 'peace and love'
  expiresIn: '7d'

SESSION:
  secret: 'no wars'
  name: 'no wars.name'
