services:
  # nest-container:
  #   build:
  #     context: ./
  #     dockerfile: ./Dockerfile
  #   environment: 
  #     - RUNNING_ENV=prod
  #   depends_on:
  #     - mysql-container
  #     - redis-container
  #   ports:
  #     - '3000:3000'
  mysql-container:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=dd123456
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
  redis-container:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
volumes:
  mysql-data:
  redis-data: